apiVersion: v1
kind: ConfigMap
metadata:
  name: DevOpsCap-AWSAuth
  namespace: default
data:
  mapRoles: |
    - rolearn: arn:aws:iam::568283627415:role/DevOpsCap-Node-NodeInstanceRole-HMPP7U7N40IM
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes