apiVersion: v1
kind: ReplicationController
metadata:
 name: green
 labels:
  app: green
spec:
 replicas: 1
 selector:
  app: green
 template:
  metadata:
   labels:
    app: green
  spec:
   containers:
    - name: green
      image: pessniam/DevOpsCap
      ports:
      - name: "https-server"
        containerPort: 80