Description:
    EKS Cluster Configuration
    
Parameters:
    StackName:
      Type: String
      Description: Resource Name Identifier
      
Resources:
    EksServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - eks.amazonaws.com
            Action:
            - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
          - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
          - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
          
    EksCluster:
      Type: AWS::EKS::Cluster
      Properties:
        Version: '1.15'
        RoleArn: !GetAtt EksServiceRole.Arn
        ResourcesVpcConfig:
          SecurityGroupIds:
          - Fn::ImportValue:
              !Sub ${StackName}-CLUSTER-SG
          SubnetIds:
              Fn::Split:
                  - ","
                  - Fn::ImportValue:
                        Fn::Sub: ${StackName}-SUBNETS
                        
Outputs:
    RoleArn:
      Description: AmazonEKS Role for Kubernetes operations
      Value: !GetAtt EksServiceRole.Arn
      Export:
        Name: !Sub ${StackName}-EKS-RoleArn
        
    EksId:
      Description: EKS ID
      Value: !Ref EksCluster
      Export:
        Name: !Sub ${StackName}-EKS